### ISSUE TITLE
Rather a question,

### ISSUE THREAD

**Issue by wku** [arguiot/DisplayJS#1]
Do you plan to add a few concise laconic
Additions - cycles, conditions choose, routes?

**Comment by arguiot** [comment]
I’m sorry, but I don’t really get what you’re saying, could you explain? Cause I’m not an English native speaker and I don’t know some of the terms you used. 😊

**Comment by wku** [comment]
How to implement a similar construction
ng-repeat - angularjs ?

**Comment by arguiot** [comment]
Well, to be honest with you, I planned to do something similar. Cause I have a lot of work on other things, if you want to implement it, you can by doing a fork and a pull request. I think it will be much faster to do.

**Comment by arguiot** [comment]
I will do it for the version 0.2.0 of DisplayJS, and maybe earlier if you want this feature. I still have a lot of work (such as writing the documentation) and it will be awesome if you can help. Of course, your name will be on the contributors list

**Comment by wku** [comment]
Ok
I'm understood, thank you
I'll finish later
