### ISSUE TITLE
Need an example app

### ISSUE THREAD

**Issue by PascalLeMerrer** [arguiot/DisplayJS#10]
Hello

Unless I'm missing something, the given examples are too light for me to understand what a real app would look like.
Do you have any example of application created with DisplayJS?

Pascal

**Comment by arguiot** [comment]
Yes, but the one I made is not designed with all new features of DisplayJS.

It’s basically a TodoMVC example that I will post on codepen today. When it will be released, I’ll tell you 😊.

**Comment by PascalLeMerrer** [comment]
Thanks.

**Comment by arguiot** [comment]
@PascalLeMerrer I'm sorry for the response time, but I wasn't at home today 😊.

⚠️ This app doesn't use the best DisplayJS best practices, this is why I won't publish it yet on the official TodoMVC page, but you can have an idea of how DisplayJS works in production, but keep in mind that some features introduced in a newer release aren't in this demo.

You can find it [here](https://codepen.io/arguiot/project/editor/XJYxdd)
