### ISSUE TITLE
Self read elements in $.on, $.html and other

### ISSUE THREAD

**Issue by ange007** [arguiot/DisplayJS#11]
It would be good if elements were read out by a call of $ .on(), $ .html() and others. 
As now it very much spoils a code.

> $.html($.s(".todo-list"), localStorage.getItem("todos"));
> $.all($.s(".toggle"), function(el) {});

**Comment by arguiot** [comment]
I don’t really understand your point, could you develop please?

**Comment by ange007** [comment]
I speak about an opportunity to write:
```
$.html(".todo-list", '');
$.all(".toggle", function(el) {});
```

**Comment by arguiot** [comment]
@ange007 Cool 😎, will be in `v2.0.0` (I guess I'll have a lot of work)
