### ISSUE TITLE
How use displayJS in objects or class

### ISSUE THREAD

**Issue by ange007** [arguiot/DisplayJS#12]
Tell me please what I do not correctly *(use [example3](https://display.js.org/#example3))*?

```javascript
<script>
var $ = new DisplayJS( window );

var obj = {};
obj.set = function( )
{
    var list = $.range(5);
    var average = $.average( list );
    var median = $.median( list );
   ....
    $.var( );
};

obj.set( );
</script>
```
![_035](https://user-images.githubusercontent.com/2736539/29272569-4c968998-8109-11e7-9399-29b0e3d1c882.png)

Or it is necessary to use?:
```javascript
let data = {
  list: '',
  average: '',
  median: ''
}

const $ = new DisplayJS( data );
```

But how uses displayJS in classes and many objects?

**Comment by ange007** [comment]
I partially understood having looked at source codes of library.
Data undertake from the object transferred to displayJS.
It turns out it is necessary for each object class to create a separate copy of displayJS.

**Comment by arguiot** [comment]
There is a much more easier way to use DisplayJS in a class, because DisplayJS is actually a class.

```javascript
class newClass extends DisplayJS {
    constructor() {
        this.params = { p1: "Hello World" }
        this.$ = super(this.params);
     }
}
```

**Comment by arguiot** [comment]
And, for your initial question, the problem is the context, if you declare variables inside a function or an object, they won’t be global, they will be local. DisplayJS can’t handle local variables, you need to make them global like `var myVar` becomes `myVar`
