### ISSUE TITLE
Separation of the project code

### ISSUE THREAD

**Issue by ange007** [arguiot/DisplayJS#18]
I think it would be more convenient to carry out some functionality in "plugins". 
For example to "Math".
It concerns both "src", and a "dist" directories.

**Comment by arguiot** [comment]
Yes, you’re right, this will also optimize the size of the code. Do you think 🤔 it will be necessary to release a bundle with every plugins already in every release?

**Comment by ange007** [comment]
I think it will be good if there is a choice - "all" or "separately".

**Comment by ange007** [comment]
With it will help: [gulp-rigger](https://www.npmjs.com/package/gulp-rigger)
