### ISSUE TITLE
There is a $.select() question when i use display.es6.js

### ISSUE THREAD

**Issue by Cslove** [arguiot/DisplayJS#19]
i wanted to use $.s() function to select DOM node 

![html](https://user-images.githubusercontent.com/23312535/30477944-906c5908-9a41-11e7-9e03-a73aa3466f5b.png)
but report errors: Uncaught RangeError: Maximum call stack size exceeded
![error](https://user-images.githubusercontent.com/23312535/30477994-bfae7b74-9a41-11e7-9a1e-e47c1b282922.png)

so i checked your display.es6.js  source code found that there is a question in "isElement()"function and "select()" function.
![iselement](https://user-images.githubusercontent.com/23312535/30478159-74678d4e-9a42-11e7-84df-41702538af72.png)
![select](https://user-images.githubusercontent.com/23312535/30478484-c621e5ca-9a43-11e7-954c-e1d6cba47f96.png)

so i deleted the "el = this.s(el);" in "isElement()" function and it works!

![fix](https://user-images.githubusercontent.com/23312535/30478344-3f59d520-9a43-11e7-8f0f-d7ced9489537.png)
![work](https://user-images.githubusercontent.com/23312535/30478345-42ec9f56-9a43-11e7-817b-f43c8ea4ea79.png)

Could you check the source code?

**Comment by arguiot** [comment]
Thank you a lot!!! I recommend you to do a Pull Request, so you can be in the contributors' list 😊

**Comment by arguiot** [comment]
You know what, I will fix it myself, and I will add you manually to the contributors' list

**Comment by Cslove** [comment]
ok，thank you. i am a young novice ,too.i will study your source code again!😊

**Comment by arguiot** [comment]
@Cslove No worries, I can understand, I'm 15 years old in fact 😊

**Comment by Cslove** [comment]
wow! incredible! you are my idol

**Comment by arguiot** [comment]
@Cslove Aha 😂

**Comment by arguiot** [comment]
By the way, I fixed the `$.s()`, and I released `v2.0.1`. Oh, and don't forget to leave a star on the project, it would be very cool

**Comment by Cslove** [comment]
yes，absolutely i have already stayed！
