### ISSUE TITLE
More examples, please! 

### ISSUE THREAD

**Issue by dlewand691** [arguiot/DisplayJS#23]
Just stumbled on this today and I can see the benefits of using a framework like this. Would really love to see more examples of how it might apply to real-world situations. Things like:
- Navigation
- Personalization
- Dynamic UI elements (favorites, ratings, etc)
- Other UI tricks like animations, effects, transitions, etc

Thanks for this, will be watching!

**Comment by arguiot** [comment]
Ok, I’ll maybe provide a demo website, to see what DisplayJS is capable of 😊

**Comment by arguiot** [comment]
But I can’t say when it will be available because I have a lot of work 😊
