### ISSUE TITLE
$.component is not useful.

### ISSUE THREAD

**Issue by JZLeung** [arguiot/DisplayJS#26]
```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new component (display.js:541)
    at DisplayJS.component (display.js:550)
    at 
```

**Comment by arguiot** [comment]
Argh! I definitly need to use somethong to test everything when I release a new release (because when I tested it first, it worked). Thank you for reporting 😊.

**Comment by arguiot** [comment]
@JZLeung I tried to fix it, but the problem doesn't come from me 😊, it comes from Babel. I'm seeing with them if we can fix it (via an [issue](https://github.com/babel/babel/issues/6297), but for the moment, use `display.es6.js`, or `display.es6.min.js`, and it should work fine.

**Comment by JZLeung** [comment]
ok, I'll try it later.
In fact, the beginning I would like to express the meaning that `$.component()` is not work well, but my English is not good.
