### ISSUE TITLE
a wrong word

### ISSUE THREAD

**Issue by nile52** [arguiot/DisplayJS#28]
It's not important,but is adjascent a wrong word in $.after() & $.before()?

**Comment by arguiot** [comment]
Hum 😐, I'm not sure to understand, could you develop?

**Comment by nile52** [comment]
Maybe, adjascent should be changed to adjacent.
![image](https://user-images.githubusercontent.com/15318725/30892747-c893f4ec-a36c-11e7-9076-511a2a4a2eec.png)

**Comment by arguiot** [comment]
Yes, little mistake from me, I’m sorry. If you want to empty the stuff after, just select h1 instead of .testEl
