### ISSUE TITLE
$.empty() is not work very well

### ISSUE THREAD

**Issue by nile52** [arguiot/DisplayJS#29]
$.empty() can't empty the content which I insert by $.after() & $.before()
html
`<div class="testEl">I'll have before and after HTML when DisplayJS will do its work</div>
`
js
`$.after($.select(".testEl"), "<h1>Hello, I'm the after HTML</h1>");
$.empty($.select(".testEl"))`

**Comment by arguiot** [comment]
`$.empty()` should work, could you give me a screenshot of your DOM (like a screenshot of the Chrome Dev console)

**Comment by nile52** [comment]
![image](https://user-images.githubusercontent.com/15318725/30892553-e9e650b4-a36b-11e7-8e70-62bf355c71c3.png)

**Comment by arguiot** [comment]
Yeah, normal, you try to empty something that is already empty, try select `<h1>` instead of the element before 😊.
