### ISSUE TITLE
$.css() how to set more CSS properties for the set of matched elements.

### ISSUE THREAD

**Issue by nile52** [arguiot/DisplayJS#30]
Use the .css() function in jQuery, we can set one or more CSS properties for the set of matched elements.
Can $.css()  do the same?
```
$("p").css("color","red");
$("p").css({
  "color":"white",
  "background-color":"#98bf21",
  "font-family":"Arial",
  "font-size":"20px",
  "padding":"5px"
  });
```

**Comment by arguiot** [comment]
It’s not possible currently, but I think I’ll put it in the next release 😊.
