### ISSUE TITLE
i tried the example but i get a opposite result

### ISSUE THREAD

**Issue by nile52** [arguiot/DisplayJS#31]
![image](https://user-images.githubusercontent.com/15318725/30898890-1c431dde-a390-11e7-89e2-4b68db5bb729.png)

![image](https://user-images.githubusercontent.com/15318725/30898858-036d6c74-a390-11e7-90ce-dbc12a5cf27f.png)

**Comment by arguiot** [comment]
The example was missing something, try with:
```javascript
$.rmFromArray($.range(10), x => x % 2 == 0);
```
Should work 😊.
