### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by arguiot** [arguiot/DisplayJS#32]
Hacktoberfest is here, and DisplayJS is a perfect repo for it 😊.

**Comment by DanielTamkin** [comment]
@arguiot I'll definitely be contributing, why not add a little more to this issue to help explain what DisplayKS is all about? you're coming up as the [second result on the search right now](https://github.com/search?q=label:hacktoberfest+state:open+type:issue)! 😄

**Comment by arguiot** [comment]
DisplayJS is a simple JavaScript frameworks that is built for scale. Its syntax has some similarities with jQuery, which make it easy to use and to learn. It comes packed with great Math/Array manipulation functions (in addition to the DOM manipulation functions). DisplayJS is written in modern JS, which make  it future proof 😊.

**Comment by storbeck** [comment]
What is it that you'd like help with? There are no open issues

**Comment by DanielTamkin** [comment]
@storbeck Yeah good point eh, Or are you looking for us to Bug mine DisplayJS @arguiot?

**Comment by arguiot** [comment]
@DanielTamkin @storbeck I’m looking for you to Bug Mine, to add features. and to optimize the code 😊.

**Comment by cdikibo** [comment]
I found this through the website👀

**Comment by arguiot** [comment]
@cdikibo What did you find? 🤔

**Comment by khorramk** [comment]
can you be more specific when mean scale?

**Comment by flordeciruela** [comment]
@arguiot Hello,
I have reviewed your tests and I propose to add more, I am making a pull request with a couple more tests for "$ .math", I hope they are accepted.
:)

**Comment by arguiot** [comment]
Hacktoberfest is now finished
