### ISSUE TITLE
Repeat in array with objects

### ISSUE THREAD

**Issue by xJoeyv** [arguiot/DisplayJS#45]
Hi,

How to repeat in a array with Objects and display certain properties out of the object?  This is where Im working in to test with DisplayJS https://codepen.io/xjoeyv/pen/EbMvOJ

**Comment by arguiot** [comment]
Hello, I didn't think about this problem when I created the function repeat. But I'll probably add this feature. For now, you can just create an array, and you iterate using `for` in your to-do list Array, and you push every items in your new Array. 

I hope it's clear 😊

**Comment by xJoeyv** [comment]
@arguiot Hi, You inspired me and I started to do things like this my self, just to educate myself. I did use Lodash but maybe you can use it.

https://github.com/xJoeyv/WrittenUI/blob/dev/writtenui.js

Look at the for() method. This is way more usefull and usable. Also something like Vue has ( v-for ) would be cool. But I hope you can re-create this :)

**Comment by arguiot** [comment]
@xJoeyv That's what I'm working on it, but because I'm pretty busy, I don't have the time to write the docs, so wait until maybe Tuesday and it will be available.

**Comment by arguiot** [comment]
The update is now available.
