### ISSUE TITLE
TODO MVC challenge

### ISSUE THREAD

**Issue by unplugandplay** [arguiot/DisplayJS#49]
Hi!
did you try to solve the https://github.com/tastejs/todomvc challenge using solely displayjs ?

**Comment by arguiot** [comment]
Yes, I did. I don't know if I kept the code. But It helped me when I developed DisplayJS.

**Comment by arguiot** [comment]
I found the code, but it uses an old version of DisplayJS (it should work on the latest version). Here is the repo: https://github.com/arguiot/DisplayJS-ToDoMVC/
