### ISSUE TITLE
bloat

### ISSUE THREAD

**Issue by Nashorn** [arguiot/DisplayJS#51]
Dude,
you have a great idea for binding state between the UI and Controller. You should strip down your api to it's core driving principal of just that, binding state. You have packaged up alot of non-sense bloat that developers dont need or care about. There is .load(), .live(), .custom(), .ajax().....and on and on.

Truth is, this is an awesome idea for an api, not a framework.

**Comment by arguiot** [comment]
I totally agree with you. DisplayJS was one of my first project in JavaScript. Now, I'm focused on [ProType](https://protype.js.org), a JS framework that was inspired by Cocoa and React. You should definitely check it out if you like DisplayJS 😊.

**Comment by Nashorn** [comment]
I see. Btw, protype website is crashing on my android phone

**Comment by arguiot** [comment]
hmmm 🤔 this is weird. It shouldn't. You can still read the [docs](https://github.com/arguiot/ProType/wiki) to learn more
