### ISSUE TITLE
jsfiddle test `undefined`

### ISSUE THREAD

**Issue by 03stories** [arguiot/DisplayJS#53]
I was just trying to create the simplest possible test, and couldn't get it work :/ 
https://jsfiddle.net/a6ysdxzo/

Any idea why I'm just getting "undefined"?

**Comment by arguiot** [comment]
I really don't know. I believe the issue is with JSFiddle. Try on https://codepen.io , it will work.

I tested it today and it worked: https://codepen.io/pen?template=MvpBJp

**Comment by 03stories** [comment]
Thank you!
