### ISSUE TITLE
Load Help

### ISSUE THREAD

**Issue by muhaza** [arguiot/DisplayJS#55]
can displayJS do

$( "#b" ).load( "article.html #target" );

load target on id/class?

**Comment by arguiot** [comment]
Yes, but not in the way you wrote the code. You can write:
```js
$.load("#b", "article.html", () => {
    const page = $. single("#b")
    const target = page.querySelector("#target").cloneNode(true) // Getting the #target
    $. single("#b").innerHTML = target.innerHTML
})
```
and it should do the job

**Comment by arguiot** [comment]
Please tell me if it worked the way you expected so I can close this issue 😄

**Comment by muhaza** [comment]
Success! Thanks arguiot.
