### ISSUE TITLE
Problem with testing outside jsfiddle

### ISSUE THREAD

**Issue by niceque** [arguiot/DisplayJS#9]
Made a local try to work from scratch and have such issue

![forstoshop - 5bc__phpstormprojects_forstoshop 5d - _dev_niceque_displayjs_app js - phpstorm 2017 1 2017-08-11 14 50 05](https://user-images.githubusercontent.com/6256044/29211912-7f207282-7ea4-11e7-89e3-5b29d2ebd3b0.png)
![forstoshop - 5bc__phpstormprojects_forstoshop 5d - _dev_niceque_displayjs_index html - phpstorm 2017 1 2017-08-11 14 51 15](https://user-images.githubusercontent.com/6256044/29211920-9176bd6a-7ea4-11e7-8f52-2fd248b8f9e9.png)

 and nothing changed...

![displayjs test - google chrome 2017-08-11 14 51 47](https://user-images.githubusercontent.com/6256044/29211935-a83b250e-7ea4-11e7-835f-bbe3f51c9e31.png)

**Comment by arguiot** [comment]
Hum 🤔, do you have any error?

Maybe try to replace `var $ = new DisplayJS(window);` by `const $ = new DisplayJS(window);`. Also, try to use `v1.2.3` instead of `v1.2.2`.

Will it be possible to have the link of the thing you’re working on?

**Comment by niceque** [comment]
changed to 1.2.2 because error of display not shown there, but no difference between...
now its no way to show the link, ill try to host somewhere

**Comment by niceque** [comment]
![forstoshop - 5bc__phpstormprojects_forstoshop 5d - _dev_niceque_displayjs_index html - phpstorm 2017 1 2017-08-11 15 53 00](https://user-images.githubusercontent.com/6256044/29213785-657de004-7ead-11e7-96b0-32814508c23d.png)

**Comment by niceque** [comment]
Hmm, repeat not working with objects?

**Comment by arguiot** [comment]
So, you’re problem comes from your `app.js`? What’s in it that could block DisplayJS?

**Comment by niceque** [comment]
Not in app.js, you also can include it using script tag but all works only if app.js before body closing tag.
If in header, no result...

How can i get functionality like ng-repeat from angular that works with objects with different deep of data using repeat in DisplayJS? Thx

**Comment by arguiot** [comment]
Yes, it’s normal, all your scripts needs to be in the body.

What do you mean by deep data?

If you have complex repeating lists, I recommend using custom components, so you can simply change the data once.

In the `v2.0.0` I’m planing to support more and more HTML based features (like Angular if you see what I mean).

I apologize for the response time, I wasn’t available 😊.

**Comment by arguiot** [comment]
@niceque Any updates? can I close this issue?

**Comment by arguiot** [comment]
@niceque No updates in 24 hours, for the moment I'll close this issue, but if there is any updates, I'll reopen it 😊
