### ISSUE TITLE
Run a function when target variable changes

### ISSUE THREAD

**Issue by Hedronmx** [arguiot/DisplayJS#95]
Is it possible to call a function every time a target variable changes??

**Comment by arguiot** [comment]
Yes! It's actually written in the [docs](https://github.com/arguiot/DisplayJS/wiki/The-basics:-%24.var()---%24.target()#target)

> ⚠️ The $.target() can accept a callback function to do other things than just render, but if you're using this method, the $.var() function won't be automatically called, so don't forget to do it manually 😊.

So, you can just do:
```js
$.target(() => {
     // Do whatever here
     
     $.var() // render everything, because it won't be triggered automatically otherwise
})
```
